services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: docker
    ports:
      - 8686:8080
    volumes:
      - ./api:/api
    tty: true
    env_file:
      - .env.supabase.local
    environment:
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      DB_USER: ${SUPABASE_DB_USER}
      DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      DB_HOST: ${SUPABASE_DB_HOST}
      DB_PORT: ${SUPABASE_DB_PORT}
      DB_NAME: ${SUPABASE_DB_NAME}
