services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: docker
    ports:
      - 8686:8080
    volumes:
      - ./api:/api
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 54322
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_SSL_MODE: disable
      SUPABASE_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./web:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: development
      VITE_SUPABASE_URL: http://host.docker.internal:54321
      VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      VITE_API_BASE_URL: http://host.docker.internal:8686
      SUPABASE_API_URL: http://host.docker.internal:54321
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

  claude-code:
    profiles:
      - claude
    build:
      context: ./claude-docker
      dockerfile: Dockerfile
    container_name: topicpost-claude-code
    working_dir: /home/node/workspace
    volumes:
      - .:/home/node/workspace:cached
      - claude_node_modules:/home/node/workspace/web/node_modules
      - claude_api_cache:/home/node/workspace/api
      - claude_git_config:/home/node/.git
      - ./claude-docker/.claude:/home/node/.claude
    ports:
      - "3000:3000"
      - "8687:8686"
      - "8000:8000" 
      - "8080:8080"
    environment:
      NODE_ENV: development
      GIT_SAFE_DIRECTORY: /home/node/workspace
      CLAUDE_CODE_WORKSPACE: /home/node/workspace
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      AUTO_CLAUDE: ${AUTO_CLAUDE:-false}
    stdin_open: true
    tty: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  claude_node_modules:
    driver: local
  claude_api_cache:
    driver: local
  claude_git_config:
    driver: local
