# fly.toml app configuration file generated for topicpost-api on 2023-04-26T00:24:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "topicpost-api-stg"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
