# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Install task
      run: go install github.com/go-task/task/v3/cmd/task@latest

    - name: Generate ent code
      run: task gen

    - name: Run OpenAPI generator
      run: task ogen-go

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
